/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  SFISCInterface,
  SFISCInterfaceInterface,
} from "../SFISCInterface";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "circulatingSupply",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class SFISCInterface__factory {
  static readonly abi = _abi;
  static createInterface(): SFISCInterfaceInterface {
    return new utils.Interface(_abi) as SFISCInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): SFISCInterface {
    return new Contract(address, _abi, signerOrProvider) as SFISCInterface;
  }
}
